Onix_web/Onix_web/urls.py
# -*- coding: utf-8 -*-
"""Onix_web URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('locations/', include('locations.urls', namespace='locations')),
    path('', include('index.urls')),
    path('account/', include('accounts.urls')),
]

#  REST framework's
urlpatterns += [
    path('api/', include('locations_api.urls', namespace='locations_api')),
    path('my_auth/', include('rest_framework.urls'))
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Onix_web/index/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from index import views

urlpatterns = [
    path('', views.index_one, name='index')
]

Onix_web/locations/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from locations import views

app_name = 'locations'

urlpatterns = [
    path('', views.country_directory, name='country_directory'),
    path('country/<int:id_city>/detail', views.country_detail, name='country_detail'),
    path('city/<int:id>/detail', views.city_detail, name='city_detail'),
    path('city/<int:id>/delete', views.delete_city, name='delete_city'),
    path('add_country/', views.add_country, name='add_country'),
    path('country/<int:id>/edit', views.edit_country, name='edit_country'),
    path('add_city/', views.add_city, name='add_city'),
    path('city/<int:id>/edit', views.edit_city, name='edit_city'),
]

Onix_web/locations/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save, post_delete, pre_delete, pre_save
from django.dispatch import receiver


class Symbol(models.Model):
    image = models.ImageField(upload_to='country/%Y/%m/%d/')


class Country(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    population = models.IntegerField(default=0)
    flag = models.OneToOneField(Symbol,
                                on_delete=models.CASCADE,
                                primary_key=True,)

    cities_count = models.IntegerField(default=0)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country,
                                on_delete=models.CASCADE,)
    longitude = models.FloatField()
    latitude = models.FloatField()

    def __str__(self):
        return self.name

@receiver(pre_save, sender=City)
def city_save_signal(sender, **kwargs):
    print(f"Город {kwargs['instance']} добавлен")

@receiver(post_save, sender=City)
def city_post_save_signal(sender, instance, **kwargs):
    instance.country.cities_count += 1
    instance.country.save()

@receiver(pre_delete, sender=City)
def city_del_signal(sender, instance, **kwargs):
    instance.country.cities_count -= 1
    instance.country.save()

@receiver(post_delete, sender=City)
def city_post_del_signal(sender, instance, **kwargs):
    print(f"Город {instance} удален ")

Onix_web/locations/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from locations.models import Country, Symbol, City
from django import forms


class AddCountryForm(ModelForm):
    flag = forms.ImageField()
    class Meta:
        model = Country
        exclude = ['cities_count', 'users']

    def clean_flag(self):
        cleaned_data = self.cleaned_data
        cleaned_data = Symbol.objects.create(image=cleaned_data['flag'])
        return cleaned_data

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = '__all__'

Onix_web/locations/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from locations.models import Country, City, Symbol
from locations.forms import AddCountryForm, CityForm

@login_required
def country_directory(request):
    """list of countries"""
    category_list = Country.objects.order_by()
    return render(request, 'locations/categories_countries.html', {'categories': category_list})


@login_required
def country_detail(request, id_city):
    """country in detail"""
    try:
        country = Country.objects.get(pk=id_city)
    except City.DoesNotExist:
        pass
    return render(request, 'locations/country_detail.html', {'country': country})

@login_required
def city_detail(request, id):
    """city ​​in detail"""
    city = get_object_or_404(City, id=id)
    return render(request, 'locations/city_detail.html', {'city': city})


@login_required
def delete_city(request, id):
    """delete city"""
    city_del = get_object_or_404(City, id=id)
    country_id = city_del.country_id
    city_del.delete()
    return redirect('locations:country_detail', country_id)


@login_required
def add_country(request):
    """add country"""
    if request.method == 'POST':
        form = AddCountryForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            country = form.save()
            country.users.add(request.user)
            return redirect('locations:country_directory')
    else:
        form = AddCountryForm
    return render(request, 'locations/add_country.html', {'form': form})


@login_required
def edit_country(request, id):
    country = get_object_or_404(Country, pk=id)
    form = AddCountryForm(request.POST, instance=country)
    if request.method == 'POST':
        if form.is_valid():
            country = form.save(commit=False)
            country.save()
            return redirect('locations:country_detail', id_city=id)
    else:
        form = AddCountryForm(instance=country)
    return render(request, 'locations/edit_country.html', {'form': form})


@login_required
def add_city(request):
    """add city"""
    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            city = form.save(commit=False)
            city.save()
            return redirect('locations:country_directory')
    else:
        form = CityForm
    return render(request, 'locations/add_city.html', {'form': form})


@login_required
def edit_city(request, id):
    city = get_object_or_404(City, pk=id)
    form = CityForm(request.POST, instance=city)
    if request.method == 'POST':
        if form.is_valid():
            city = form.save(commit=False)
            city.save()
            return redirect('locations:city_detail', city.pk)
    else:
        form = CityForm(instance=city)
    return render(request, 'locations/edit_city.html', {'form': form})

Onix_web/locations/templates/locations/add_city.html
{% extends "locations/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 class="mt-4">Information about city</h1>

    <form action="{% url 'locations:add_city' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary btn-block" type="submit">Upload</button>
    </form>
{% endblock content %}

Onix_web/locations/templates/locations/add_country.html
{% extends "locations/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1 class="mt-4">Information about country</h1>

    <form action="{% url 'locations:add_country' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form_flag|crispy }}
        {{ form|crispy }}
        <button class="btn btn-primary btn-block" type="submit">Upload</button>
    </form>
{% endblock content %}

Onix_web/locations/templates/locations/base.html
{% extends 'base.html' %}
{% load static %}


{% block page %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Post Content Column -->
            <div class="col-lg-8">
                {% block content %}    {% endblock %}
            </div>

            <!-- Sidebar Widgets Column -->
            <div class="col-md-4">
                {% block sidebar %}


                {% endblock %}
            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
    <div style="padding: 15px;"></div>

{% endblock page %}

Onix_web/locations/templates/locations/categories_countries.html
{% extends "locations/base.html" %}
{% load locatios_tag %}

{% block content %}
    <title>{% block title %}Country{% endblock %}</title>
    <table class="table mt-4">

        <thead>
        <tr>
            <th scope="col"><h1>List countries </h1></th>
            <th scope="col"></th>
        </tr>
        </thead>
        {% for countries in categories %}
            <tr>
                <th scope="col">
                    <li><a href="{% url 'locations:country_detail' countries.pk %}">{{ countries.name }}</a></li>
                </th>
                <td scope="col"><a href="{% url 'locations:edit_country' countries.pk %}">edit</a></td>
            </tr>

        {% endfor %}

    </table>

    <a type="button" class="btn btn-primary btn-lg btn-block" href="{% url 'locations:add_country' %}">Add country</a>

{% endblock content %}
{% block sidebar %}
    <h1 class="mt-4"> Represented countries: {% my_count_country_tag %} </h1>
{% endblock sidebar %}

Onix_web/locations/templates/locations/city_detail.html
{% extends "locations/base.html" %}

{% block content %}
    <title>{% block title %}City{% endblock %}</title>
    <body>

    <h1 class="mt-4"> {{ city.name }} </h1>
    <p class="date">Geographical coordinates: (latitude - {{ city.latitude }}, longitude - {{ city.longitude }}) </p>

    <a type="button" class="btn btn-secondary btn-lg btn-block" href="{% url 'locations:delete_city' city.id %}">delete
        city {{ city.name }}</a>

    </body>
{% endblock content %}

Onix_web/locations/templates/locations/country_detail.html
{% extends "locations/base.html" %}


{% block content %}
    <title>{% block title %}City{% endblock %}</title>
    <body>
    <h1 class="mt-5">{{ country.name }}</h1>
    <p>{{ country.description|truncatewords_html:80 }}</p>
    <h5>population: {{ country.population }}</h5>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">City:</th>
            <th scope="col"></th>
        </tr>
        </thead>
        {% for city in country.city_set.all %}
            <tr>
                <th scope="col"><a href="{% url 'locations:city_detail' city.id %}">{{ city }}</a></th>
                <td scope="col"><a href="{% url 'locations:edit_city' city.pk %}"><span class="oi oi-pencil"></span>edit</a>
                </td>
            </tr>
        {% endfor %}
    </table>

    <a type="button" class="btn btn-primary btn-lg btn-block" href="{% url 'locations:add_city' %}">Add city</a>

    </body>
{% endblock content %}
{% block sidebar %}
    <img class="mt-5" src="{{ country.flag.image.url }}" width="400" height="200"/><br>
{% endblock %}

Onix_web/locations/templates/locations/edit_city.html
{% extends "locations/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 class="mt-4">Edit city</h1>

    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary btn-block" type="submit">Update</button>
    </form>
{% endblock content %}

Onix_web/locations/templates/locations/edit_country.html
{% extends "locations/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 class="mt-4">Edit country</h1>

    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary btn-block" type="submit">Update</button>
    </form>
{% endblock content %}